### ISSUE TITLE
주제,기능  정하기 4시

### ISSUE THREAD

**Issue by tjdanqkr** [hk-toss-full/java-study#5]
[양태양, 유윤지, 김송하, null, 조예은, 박서영]  미니게임 
[조서연, 조경준, 노영현, 서승주, 서한승, 김현정] 편의점 타이쿤
[이채민, 손지원, 이세연, 이주형, 김민석, 양예현] 펫 키우기
[null, 이현숙, null, 최승혁, 최창환, 이승진] 승강기

**Comment by tjdanqkr** [comment]
1. 반복
2. 조건
3. 자료구조 (list, set, queue, stack, map)
4. thread
5. scanner
6. enum, interface

**Comment by tjdanqkr** [comment]
주제를 랜덤 받을거고 
월요일 9 시 ~ 4시 까지 
요구사항은 이거였는데 이렇게 했어요 발표

**Comment by tjdanqkr** [comment]
평가 내용:
1. 완성도 (10)
2. 주제 팀의 평가 (10)
3. 코드 (10)
4. 업무분담 (10)
5. 팀의 성장도 (10)

**Comment by bbungjin** [comment]
https://spiny-dedication-748.notion.site/10e6889743948001b6b0eb27df9951c1?pvs=4

**Comment by G0sim** [comment]
[양태양, 유윤지, 김송하, null, 조예은, 박서영] : 미니게임 만들기

스도쿠 게임
난이도 설정 가능 : 초급(숫자 40개) / 중급(20개) / 고급(10개)
제한시간(필수) 설정 : 난이도에 따라 차이 존재(시간 길이 : 초>중>고)
제한시간이 모두 지나면 게임이 종료되어야함
게임을 시작하면 9*9 크기로 스도쿠 판이 화면에 나타나며, 미리 채워진 숫자가 존재함. 채워진 숫자의 개수는 난이도마다 차이가 있음
틀린 숫자를 잘못된 장소에 입력하면 기회가 차감됨. 기회는 한 게임당 총 3번. 기회를 모두 소진하면 게임이 종료되어야함
숫자는 (숫자, x좌표, y좌표)로 입력
모든 칸을 채우면 게임이 종료되어야함

십자말풀이 게임
제한시간(필수) 설정 : 20분
제한시간이 모두 지나면 게임이 종료되어야함
게임에는 총 단어가 10개 이상 포함되어야함
단어의 경우, 3글자 이상이어야 하며, 3글자 단어는 4개 이하로 제한함.
단어 각각에는 단어의 방향(가로/세로)과, 단어가 시작되는 좌표와, 단어의 설명이 화면에 표시되어야함
예시 : 가로
[2,2] 설명
[3,6] 설명
...
세로
[1,2] 설명
[6.8] 설명
...
힌트를 사용하면 단어에 대해 초성을 표시해줌
예시: ㄱㄹㄱ(기러기), ㄱㅇ(가위) 등
힌트는 3개로 제한됨
넘버링을 지정하여 단어를 입력
답이 아닌 경우, 기회를 1회 차감함. 기회는 한 게임당 총 3번이며 기회를 모두 소진하면 게임이 종료됨
모든 칸이 채워지면 게임이 종료됨
답을 맞춘 경우, 화면의 십자말풀이 판에 해당 단어가 채워진 상태로 표시되어야함
십자 말풀이에서 일정 시간이 지나면 빈 칸 단어가 자동으로 추가 되며, 만약 빈칸을 컴퓨터가 더 많이 채우면 컴퓨터 우승


<img width="141" alt="스크린샷 2024-09-27 오후 4 10 21" src="https://github.com/user-attachments/assets/229a4317-d7b4-4b54-8568-d2bd47fded73">


<img width="139" alt="스크린샷 2024-09-27 오후 4 10 31" src="https://github.com/user-attachments/assets/f3e5e429-a81b-4613-82aa-a017789e33e5">

**Comment by seunzu** [comment]
[조서연, 조경준, 노영현, 서승주, 서한승, 김현정] 편의점 타이쿤
> 무인 편의점이라 손님은 1~5명 오고 구매이름(ex. 과자), 개수가 랜덤
> 시재금과 임대료는 고정값
> 편의점 현황(재고 관리)은 60초로 제약

만약 손님이 3명 오기로 정해져 있는데 팔 수 있는 수량이 없으면 종료 즉, 장부 출력


![스크린샷 2024-09-27 160404](https://github.com/user-attachments/assets/a2705f48-159d-475f-992f-89504604cb1c)
![스크린샷 2024-09-27 160418](https://github.com/user-attachments/assets/9605079b-8664-49ab-b158-ac3df16b5cfb)

```
================장부=================
=====================================
            일시: 24년 09월 27일
            운영 시간: 30초
            시재금: 200,000원
=====================================
판매내역
  이름      | 개수 |  금액  |  총액
--------------------------------------
  과자      |  3   | 1000원 | 3000원
아이스크림  |  1   |  500원 |  500원
=====================================
매출액
                              3500원
=====================================
발주내역
  이름      | 개수 |  금액  |  총액
-------------------------------------
  과자      |  5   |  500원 | 2500원
아이스크림  |   1  |  500원 | 500원
=====================================
발주금액
                               3000원
=====================================
임대료
                           -100,000원
=====================================
순수익
                                500원
계
                             100,500원
=====================================
재고
  이름      | 개수 |  금액  |  총액
-------------------------------------
  과자      |  2   | 500원  | 1000원
=====================================

축하합니다 ~! 당신은 장사의 신 !
// IF 마이너스, 임대료를 내지 못해 장사가 망했습니다
// IF 0원, 임대료를 냈으나 번 돈이 없습니다
```

**Comment by Chaemin-L** [comment]
- 가상 펫 어플리케이션
	- 펫 뽑기 & 이름설정
		- 랜덤으로 펫을 선택하며, 이름을 설정 (최대 10자)
		- 종류
			- 푸들
			- 포메라니안
			- 시츄
	- 사용자 정보
		- 보유 코인 (초기 100)
		- 보유 사료 (초기 사료 3)
	- 1. 집 - 펫
		- 상태
			- 포만감: 0~100 (20일 경우 굶주림, 100일 경우 포만)
			- 청결도: 0~100 (20일 경우 목욕 필요)
			- 성장 레벨: 1~5 (레벨업 시 새로운 액션 해금)
			    - 레벨업 조건: 초기 100 경험치, 이후 \*1.2배씩
		- 액션
			- 밥 주기: 사료 - 1, 포만감 100%, 경험치 +10
			- 씻겨주기: 청결도 +100%, 경험치 +10
			- 산책하기: 포만감 -20
			- 훈련: 훈련도구-1, 포만감 -30
				- 타자연습 (직업) like 끄투
					- 라운드별 제한시간 내에 주어진 문장을 입력
					- 10초를 초기값으로 라운드를 거듭할 수록 0.8배로 제한시간이 줄어듦
					- 버틴 시간의 특정 비율로 코인/경험치 획득
						- 코인 획득 비율: 기본 도구 \*10배, 고급 도구 \*12배
						- 경험치 획득 비율: 기본 도구 \*1배, 고급 도구 \*1.2배
	- 2. 상점
		- 액션
			- 사료 사기: 저급 사료 50코인, 중급사료 100코인, 고급 사료 150 코인
			- 옷 사기: 기본 옷 200 코인, 특별 옷 400 코인
			- 훈련 도구 사기: 기본 도구 30 코인, 고급 도구 60 코인

	- 3. 병원 
		- 액션
			- 주사 맞기: 병 해결. 300코인
	
	- 4. 도박장 (유흥)
		- 홀짝 맞추기
			- 각 라운드별 거는 판돈 - 사용자 정의 
			- 맞추면  2배 - 4배 - 8배
			- 못맞추면 판돈 잃음


	- 사용자가 액션을 수행할 때마다 상태가 변화하며, 주기적으로(10분마다) 펫의 상태 체크(쓰레드 활용^^)
	    - 포만감: -0.1/sec
	    - 청결도: -0.1/sec (최대 100)
	    - 병 발생: 랜덤 10분에서 60분 사이

- 강아지 종류, 옷과 같은 디자인적인 요소는 알아서 차이를 둘 수 있도록 해주시면 됩니다. 
- 무슨 액션을 하든 화면에는 항상 포만감, 청결도, 병발생 유무는 노출되어야합니다.

**Comment by tjdanqkr** [comment]
[미니게임, 편의점 타이쿤, 승강기, 펫 키우기]

**Comment by tjdanqkr** [comment]
## 편의점 타이쿤
[https://github.com/hk-toss-full/java-team2](url)

평가 내용:
1. 완성도 (10) 7
2. 주제 팀의 평가 (10) 7
3. 코드 (10) 6
4. 업무분담 (10) 8
5. 팀의 성장도 (10) 9 



문제 : controller(귀) -> service (시냅스) -> repo(뇌)
 시냅스가 귀를 컨트롤 하고 있음 

```
public class StoreService {

    private final CustomerController customerController = CustomerController.getInstance();
    private final DisplayController displayController = DisplayController.getInstance();

```
총 : 39

## 펫 키우기

[https://github.com/hk-toss-full/java-team4](url)

평가 내용:

1. 완성도 (10) 9
2. 주제 팀의 평가 (10) 8
3. 코드 (10) 7
4. 업무분담 (10) 9
5. 팀의 성장도 (10) 9

문제 :  static 너무 많음 , interface

총 : 42

## 미니게임

[https://github.com/hk-toss-full/java-team1](url)

평가 내용:

1. 완성도 (10) 8
2. 주제 팀의 평가 (10) 10   
3. 코드 (10) 5
4. 업무분담 (10) 9
5. 팀의 성장도 (10) 9 

문제 :  main 2개 

총 : 41

## 승강기

[https://github.com/hk-toss-full/java-team3](url)

평가 내용:

1. 완성도 (10) 6
2. 주제 팀의 평가 (10) 9
3. 코드 (10) 7
4. 업무분담 (10) 9
5. 팀의 성장도 (10)  9

문제 :  확실히 class 에서 해야할 일인지 생각하고 코드 분할을 좀 ....

총 : 40



# all 
 확실히 class 에서 해야할 일인지 생각하고 코드 분할을 좀 ....
